server:
  port: ${PORT:8080}

spring:
  profiles:
    active: ${PROFILE:development}

jwt:
  secret: YzNlNjVkZTQ3YjEyNWY5MWVmNWE2MjQyMzRiYmE4NTRmNGY0N2EzMDc3ZTIwYTUxNjM3ZGI0YTgyZWYyNjA0Mg==

rollbar:
  token: {ROLLBAR_TOKEN:}