spring:
  output:
    ansi:
      enabled: always
  thymeleaf:
    check-template-location: 'false'
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}
base:
  url: /api
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
server:
  tomcat:
    keep-alive-timeout: '120000'