spring:
  datasource:
    username: user
    url: jdbc:h2:mem:project5DB;DB_CLOSE_ON_EXIT=FALSE
    password: password
rollbar:
  token: ''
jwt:
  secret: YzNlNjVkZTQ3YjEyNWY5MWVmNWE2MjQyMzRiYmE4NTRmNGY0N2EzMDc3ZTIwYTUxNjM3ZGI0YTgyZWYyNjA0Mg==
